# Generated by Django 5.2.8 on 2025-11-13 13:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id_aluno', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'alunos',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nome_departamento', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'departamentos',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id_professor', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('link_citations', models.CharField(blank=True, max_length=500, null=True)),
                ('departamento', models.ForeignKey(blank=True, db_column='id_departamento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professores', to='core.departamento')),
                ('usuario', models.OneToOneField(blank=True, db_column='id_prof', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'professores',
            },
        ),
        migrations.CreateModel(
            name='AlunoProj',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ativo', models.BooleanField(default=True)),
                ('datainicio', models.DateField(default=django.utils.timezone.now)),
                ('aluno', models.ForeignKey(db_column='id_aluno', on_delete=django.db.models.deletion.CASCADE, to='core.aluno')),
            ],
            options={
                'db_table': 'aluno_proj',
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to='core.curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='departamento',
            field=models.ForeignKey(db_column='id_departamento', on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='core.departamento'),
        ),
        migrations.CreateModel(
            name='HistAluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_disciplina', models.CharField(max_length=20)),
                ('aprovado', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(db_column='id_aluno', on_delete=django.db.models.deletion.CASCADE, to='core.aluno')),
                ('departamento', models.ForeignKey(db_column='id_departamento', on_delete=django.db.models.deletion.CASCADE, to='core.departamento')),
            ],
            options={
                'db_table': 'hist_alunos',
            },
        ),
        migrations.CreateModel(
            name='ProfessorLattes',
            fields=[
                ('professor', models.OneToOneField(db_column='id_professor', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.professor')),
                ('cod_lattes', models.CharField(max_length=50, unique=True)),
                ('subarea', models.CharField(blank=True, max_length=150, null=True)),
                ('link', models.URLField(max_length=500)),
                ('palavras_chave', models.TextField(blank=True, help_text='Palavras-chave de pesquisa, separadas por vírgula')),
            ],
            options={
                'db_table': 'professores_lattes',
            },
        ),
        migrations.CreateModel(
            name='Orientador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ativo', models.BooleanField(default=True)),
                ('datainicio', models.DateField(default=django.utils.timezone.now)),
                ('professor', models.ForeignKey(db_column='id_prof', on_delete=django.db.models.deletion.CASCADE, to='core.professor')),
            ],
            options={
                'db_table': 'orientador',
            },
        ),
        migrations.CreateModel(
            name='Assessor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ativo', models.BooleanField(default=True)),
                ('datainicio', models.DateField(default=django.utils.timezone.now)),
                ('professor', models.ForeignKey(db_column='id_prof', on_delete=django.db.models.deletion.CASCADE, to='core.professor')),
            ],
            options={
                'db_table': 'assessores',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id_proj', models.AutoField(primary_key=True, serialize=False)),
                ('tema', models.CharField(default='', max_length=255)),
                ('tipo', models.IntegerField(choices=[(1, 'Iniciação Científica'), (2, 'Trabalho de Conclusão de Curso'), (3, 'Mestrado'), (4, 'Doutorado'), (5, 'Extensão')], default=1)),
                ('resumo', models.TextField(default='')),
                ('duracao', models.IntegerField(default=12, help_text='Duração em meses')),
                ('palavra_chave', models.CharField(blank=True, max_length=255, null=True)),
                ('bolsa', models.CharField(blank=True, choices=[('FEI', 'FEI'), ('CNPQ', 'CNPq'), ('FAPESP', 'FAPESP')], max_length=10, null=True)),
                ('pendencia', models.IntegerField(choices=[(1, 'Esperando aprovação da Coordenação'), (2, 'Esperando aprovação do assessor'), (3, 'Esperando aprovação do RH'), (4, 'Aprovado'), (5, 'Cancelado'), (6, 'Finalizado'), (7, 'Esperando relatório parcial'), (8, 'Esperando resposta do assessor ao relatório parcial'), (9, 'Esperando relatório final'), (10, 'Esperando resposta do assessor ao relatório final'), (11, 'Esperando assinaturas')], default=1)),
                ('mongo_id', models.CharField(blank=True, db_column='_id', max_length=24, null=True, unique=True)),
                ('melhor_corretor', models.TextField(blank=True, help_text='Texto retornado pela função de melhor corretor', null=True)),
                ('alunos', models.ManyToManyField(related_name='projetos', through='core.AlunoProj', to='core.aluno')),
                ('assessores', models.ManyToManyField(related_name='projetos_assessorados', through='core.Assessor', to='core.professor')),
                ('orientadores', models.ManyToManyField(related_name='projetos_orientados', through='core.Orientador', to='core.professor')),
            ],
            options={
                'db_table': 'projetos',
            },
        ),
        migrations.AddField(
            model_name='orientador',
            name='projeto',
            field=models.ForeignKey(db_column='id_proj', on_delete=django.db.models.deletion.CASCADE, to='core.projeto'),
        ),
        migrations.AddField(
            model_name='assessor',
            name='projeto',
            field=models.ForeignKey(db_column='id_proj', on_delete=django.db.models.deletion.CASCADE, to='core.projeto'),
        ),
        migrations.AddField(
            model_name='alunoproj',
            name='projeto',
            field=models.ForeignKey(db_column='id_proj', on_delete=django.db.models.deletion.CASCADE, to='core.projeto'),
        ),
        migrations.AlterUniqueTogether(
            name='orientador',
            unique_together={('professor', 'projeto')},
        ),
        migrations.AlterUniqueTogether(
            name='assessor',
            unique_together={('professor', 'projeto')},
        ),
        migrations.AlterUniqueTogether(
            name='alunoproj',
            unique_together={('aluno', 'projeto')},
        ),
    ]
