# Generated by Django 5.2.7 on 2025-11-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professorlattes',
            name='nome',
        ),
        migrations.AlterField(
            model_name='professorlattes',
            name='subarea',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='duracao',
            field=models.IntegerField(default=12, help_text='Duração em meses'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='resumo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tema',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Iniciação Científica'), (2, 'Trabalho de Conclusão de Curso'), (3, 'Mestrado'), (4, 'Doutorado'), (5, 'Extensão')], default=1),
        ),
    ]
